# Generated by Django 4.1.1 on 2022-12-04 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('timeinit', models.TimeField(null=True)),
                ('timefinal', models.TimeField(null=True)),
                ('especialidade', models.CharField(choices=[('Angiologia', 'Angiologia'), ('Dermatologia', 'Dermatologia'), ('Endocrinologia', 'Endocrinologia'), ('Gastroenterologia', 'Gastroenterologia'), ('Ginecologia e obstetrícia', 'Ginecologia e obstetrícia'), ('Oftalmologia', 'Oftalmologia'), ('Ortopedia', 'Ortopedia'), ('Otorrino', 'Otorrino'), ('Pediatria', 'Pediatria'), ('Psicologia', 'Psicologia'), ('Psiquiatria', 'Psiquiatria'), ('Neurologia', 'Neurologia'), ('Nutricionista', 'Nutricionista'), ('Urologia', 'Urologia'), ('Outros', 'Outros')], max_length=255, null='True')),
                ('endereco', models.CharField(max_length=255, null=True)),
                ('info', models.CharField(blank=True, default='', max_length=255000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(choices=[('MarcaConsulta', 'Marcar consulta')], max_length=255, null='True')),
                ('text', models.CharField(max_length=255, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albuns.album')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('albuns', models.ManyToManyField(to='albuns.album')),
            ],
        ),
    ]
