# Generated by Django 4.1.3 on 2022-11-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='author',
        ),
        migrations.AddField(
            model_name='list',
            name='desc',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
