# Generated by Django 4.1.1 on 2022-12-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='name',
        ),
        migrations.RemoveField(
            model_name='album',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='album',
            name='release_year',
        ),
        migrations.AddField(
            model_name='album',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
