# Generated by Django 4.1.1 on 2022-12-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0002_remove_album_name_remove_album_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='info',
            field=models.CharField(max_length=255000, null=True),
        ),
    ]
