# Generated by Django 4.1.1 on 2022-12-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0003_alter_album_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='info',
            field=models.CharField(blank=True, default='', max_length=255000),
        ),
    ]
