# Generated by Django 4.1.1 on 2022-12-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0004_alter_album_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='date',
        ),
        migrations.RemoveField(
            model_name='album',
            name='time',
        ),
        migrations.AddField(
            model_name='album',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
