# Generated by Django 4.1.1 on 2022-12-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0005_remove_album_date_remove_album_time_album_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='datetime',
        ),
        migrations.AddField(
            model_name='album',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
