# Generated by Django 4.1.1 on 2022-12-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0006_remove_album_datetime_album_date_album_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='especialidade',
            field=models.CharField(choices=[('AN', 'Angiologia'), ('DE', 'Dermatologia'), ('EN', 'Endocrinologia'), ('GA', 'Gastroenterologia'), ('GI', 'Ginecologia e obstetrícia'), ('OF', 'Oftalmologia'), ('OR', 'Ortopedia'), ('OT', 'Otorrino'), ('PE', 'Pediatria'), ('PSI', 'Psicologia'), ('PSQ', 'Psiquiatria'), ('NE', 'Neurologia'), ('NU', 'Nutricionista'), ('UR', 'Urologia'), ('OU', 'Outros')], max_length=255, null='True'),
            preserve_default='True',
        ),
    ]
