# Generated by Django 4.1.1 on 2022-12-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0008_album_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='post_date',
        ),
        migrations.AddField(
            model_name='review',
            name='especialidade',
            field=models.CharField(choices=[('MarcaConsulta', 'Marcar consulta')], max_length=255, null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='album',
            name='especialidade',
            field=models.CharField(choices=[('Angiologia', 'Angiologia'), ('Dermatologia', 'Dermatologia'), ('Endocrinologia', 'Endocrinologia'), ('Gastroenterologia', 'Gastroenterologia'), ('Ginecologia e obstetrícia', 'Ginecologia e obstetrícia'), ('Oftalmologia', 'Oftalmologia'), ('Ortopedia', 'Ortopedia'), ('Otorrino', 'Otorrino'), ('Pediatria', 'Pediatria'), ('Psicologia', 'Psicologia'), ('Psiquiatria', 'Psiquiatria'), ('Neurologia', 'Neurologia'), ('Nutricionista', 'Nutricionista'), ('Urologia', 'Urologia'), ('Outros', 'Outros')], max_length=255, null='True'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
