# Generated by Django 4.1.1 on 2022-12-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0009_remove_review_post_date_review_especialidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='time',
            new_name='timefinal',
        ),
        migrations.AddField(
            model_name='album',
            name='timeinit',
            field=models.TimeField(null=True),
        ),
    ]
